name: Markdown Lint Check

on:
  push:
    paths:
      - '**.md'

jobs:
  lint:
    runs-on: ubuntu-22.04
    env:
      CI: true
      
    steps:
    - name: Setup Action
      uses: actions/checkout@v3
      
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        
    - name: Install dependencies
      run: npm install
      
    - name: Run linter
      run: npm test
